"""Add candidate feedback fields

Revision ID: 07d6f12ecad1
Revises: 89f688597ead
Create Date: 2026-02-19 11:30:49.836443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d6f12ecad1'
down_revision = '89f688597ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('feedback_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('feedback_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('feedback_at')
        batch_op.drop_column('feedback_note')
        batch_op.drop_column('feedback_reason')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
