"""Initial schema

Revision ID: 89f688597ead
Revises: 
Create Date: 2026-02-12 16:33:54.476785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f688597ead'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amplemarket_id', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('current_title', sa.String(length=255), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('experience_summary', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_reasoning', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('outreach_message', sa.Text(), nullable=True),
    sa.Column('outreach_generated_at', sa.DateTime(), nullable=True),
    sa.Column('source_list', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amplemarket_id')
    )
    op.create_table('scoring_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=False),
    sa.Column('candidates_scored', sa.Integer(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoring_runs')
    op.drop_table('candidates')
    # ### end Alembic commands ###
